version: '3.8'

services:
  wb-parser-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./project/.env
    volumes:
      - ./project:/app/project
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ../frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wb-parser-app
